postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak

keycloak:
    image: jboss/keycloak-postgres
    links:
    - postgres:postgres
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
    ports:
    - 8080:8080
    - 8443:8443

portal:
    build: portal/
    ports:
    - "80:8080"
    environment:
        SERVICE_CELL_EXECUTION:
        KEYCLOAK_SERVER_URL:
