version: '2.1'

services:

    cellexecutor:
        build: ../components/cell-executor/build/docker
        depends_on:
        - coreservices
        - rabbitmq
        - chemservices
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/work:/tmp/work
        - /var/grape_repo
        environment:
            DOCKER_HOST: unix:///var/run/docker.sock
            SQUONK_DOCKER_WORK_DIR:
            registry.url: https://index.docker.io/v1/


