db:
    build: postgres/
    ports: 
    - "5432:5432"

cs:
    build: ../components/core-services/core-services-server/build
    ports:
    - 80:8080
    links:
    - db:db
    environment:
        CHEMCENTRAL_DB_NAME: unittest
        CHEMCENTRAL_DB_USERNAME: tester
        CHEMCENTRAL_DB_PASSWORD: "lacrocks"
        CHEMCENTRAL_AUTO_CREATE: "true"


