mq:
    image: squonk/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    environment: 
        RABBITMQ_ERLANG_COOKIE: topsecret
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: squonk


db:
    build: postgres/
    ports: 
    - "5432:5432"

cs:
    build: ../components/core-services-server/build
    ports:
    - 80:8080
    links:
    - db:db
    - mq:rabbitmq
    environment:
        RABBITMQ_HOST: mq
        SQUONK_DB_SERVER: db

