version: '2.1'

services:

    postgres:
        image: informaticsmatters/rdkit_cartridge:Release_2016_03_1
        volumes:
        - ./deploy/images/postgres/init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh:ro
        ports: 
        - "5432:5432"
        environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
