db:
    build: postgres/
    ports: 
    - "5432:5432"

cs:
    build: ../components/core-services-server/build
    ports:
    - 80:8080
    links:
    - db:db
    environment:
        SQUONK_DB_SERVER: db


