db:
    image: postgres:9.5
    volumes:
    - ./deploy/init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh:ro
    ports: 
    - "5432:5432"

mq:
    image: squonk/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "./rabbitmq/clean.sh:/usr/local/etc/clean.sh:ro"
    environment: 
        RABBITMQ_ERLANG_COOKIE: topsecret
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: squonk

chemservices:
    image: squonk/chem-services-basic
    ports:
    - "8092:8080"

cs:
    build: ../components/core-services-server/build
    ports:
    - 80:8080
    links:
    - db:db
    - mq:rabbitmq
    - chemservices:chemservices
    environment:
        RABBITMQ_HOST: mq
        SQUONK_DB_SERVER: db

