db:
    image: informaticsmatters/rdkit_cartridge:Release_2016_03_1
    volumes:
    - ./deploy/images/postgres/init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh:ro
    ports: 
    - "5432:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres

rabbitmq:
    image: squonk/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "./rabbitmq/clean.sh:/usr/local/etc/clean.sh:ro"
    environment: 
        RABBITMQ_ERLANG_COOKIE: topsecret
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: squonk

chemservices:
    build: ../components/build/chem-services-basic
    ports:
    - "8092:8080"

coreservices:
    build: ../components/core-services-server/build
    ports:
    - 8091:8080
    links:
    - db:db
    - rabbitmq:rabbitmq
    - chemservices:chemservices
    environment:
        RABBITMQ_HOST: rabbitmq
        SQUONK_DB_SERVER: db

cellexecutor:
    build: ../components/cell-executor/build/docker
    links:
    - coreservices:coreservices
    - rabbitmq:rabbitmq
    - chemservices:chemservices
    environment:
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_SQUONK_PASS: squonk
        SQUONK_SERVICES_CORE: http://coreservices:8080/coreservices/rest/v1


