rabbitmq:
    build: .
    ports:
    - "5672:5672"
    - "15672:15672"
#    volumes:
#    - ./init.sh:/usr/local/etc/init.sh:ro
#    - ./update-credentials.sh:/usr/local/etc/update-credentials.sh:ro
    environment: 
        RABBITMQ_ERLANG_COOKIE: topsecret

