# You must set the host environment variable for DOCKER_GATEWAY
# It will be something like 172.17.0.1
# To find out do a:
# docker network inspect bridge
#
# To build the docker images move to the directory above this and run:
# ./build-internal.sh     <--- builds the containers containing our code
# ./build-external.sh     <--- builds the postgres and rabbitmq containers (should only need doing once)


################# Rabbit MQ container #############################################
mq:
    image: squonk/rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
    hostname: rabbitmq
    environment: 
        RABBITMQ_ERLANG_COOKIE: topsecret

################# PostgreSQL container ############################################
db:
    image: squonk/postgres
    ports: 
    - "5432:5432"

################# core services container #########################################
# available on:
# http://${DOCKER_GATEWAY}/coreservices/rest/ping
# http://${DOCKER_GATEWAY}/coreservices/rest/v1/services
# http://${DOCKER_GATEWAY}/coreservices/rest/v1/jobs
# 
cs:
    image: squonk/core-services
    ports:
    - 80:8080
    links:
    - db:db
    - mq:rabbitmq
    environment:
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_VHOST: "/unittest"
        RABBITMQ_USER: tester
        RABBITMQ_PASSWORD: lacrocks
        SQUONK_DB_SERVER: db
        SQUONK_BASIC_CHEM_SERVICES_URL: "http://${DOCKER_GATEWAY}:9080"
#        SQUONK_RDKIT_CHEM_SERVICES_URL

################# chem services container #########################################
# available on
# http://${DOCKER_GATEWAY}:9080/chem-services-rdkit-basic/rest/v1/calculators
# http://${DOCKER_GATEWAY}:9080/chem-services-cdk-basic/rest/v1/calculators
# http://${DOCKER_GATEWAY}:9080/chem-services-chemaxon-basic/rest/v1/calculators
# http://${DOCKER_GATEWAY}:9080/chem-services-chemaxon-basic/rest/v1/descriptors
#
# Test using something like this:
# curl -X POST -T mols.json "http://${DOCKER_GATEWAY}:9080/chem-services-cdk-basic/rest/v1/calculators/logp"
#
chemservices:
    image: squonk/chem-services-basic
    ports:
    - "9080:8080"

################# swagger container ###############################################
swagger:
    image: sjeandeaux/docker-swagger-ui
    ports:
        - "8888:8888"
    environment: 
        API_URL: http://${DOCKER_GATEWAY}/coreservices/api-docs
        

