
################# rdkit server services container ##################################
# test using:
# curl -X POST -T mols.json -H "Accept: application/json" -H "Content-Type: application/json" "http://localhost:8000/rdkit_cluster/cluster_simple?metric=tanimoto&threshold=0.7
#
rdkitserver:
    image: squonk/rdkitserver
    restart: always
    ports:
    - "8000:8000"
    environment: 
        SECRET_KEY:
        C_FORCE_ROOT: "true"
    command: gunicorn -w 3 -b 0.0.0.0 proj.wsgi
    volumes:
    - /code/static

coreservices:
    links:
    - rdkitserver:rdkitserver
    environment:
        SQUONK_RDKIT_CHEM_SERVICES_URL: "http://rdkitserver:8000"  # internal port

cellexecutor:
    links:
    - rdkitserver:rdkitserver
